### PR TITLE
The default for the Treeview dataUrlField is 'url'

### PR DESCRIPTION
**Pull request by dandv**
As demonstrated by this demo - http://dojo.telerik.com/AciYo

### CODE REVIEW

**Comment by dandv** [comment]
Not sure this is a bug, but [setting dataUrlField to null has no effect - the `url` field will still be interpreted](http://dojo.telerik.com/@dandv/IJEBE).

**Comment by KirilNN** [comment]
Hi @dandv 

The value accept a string and I am afraid that we will not be able to accept this pull request.

**Comment by dandv** [comment]
Agree that the `dataUrlField` accepts a String value. But what is the default for that value, if not specified explicitly? `null` or the string `'url'`?

**Comment by gyoshev** [comment]
The default value is null. When it is set to a falsy value, the `url` field will be used, due to legacy.

**Pull request closed without merging**
